// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace TwoMinGameplayTag
{
	// Input Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CounterAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle);		// Toggle
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Run);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_LockOn);

	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHold);	// Hold
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHold_Guard);

	// Weapon Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Shield);
	
	// Player Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LightAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HeavyAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_CountAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LockOn);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);

	// Player Event Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	
	// Player State Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_LockOn);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Rolling);
	
	// Enemy Weapon Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	// Enemy Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee_1);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee_2);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee_3);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Detect);

	// Enemy Cooldown Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Cooldown_Ability_Melee_1);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Cooldown_Ability_Melee_2);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Cooldown_Ability_Melee_3);
	
	// Shard Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Guard);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Exhausted);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_PerfectGuard);

	// Shard SetByCaller
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	
	// Shard Event Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitGuard)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Exhausted);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SuccessPerfectGuard);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Death);

	// Shard State Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Invincible);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_UnBreakAttack);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Guarding);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Exhausted);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_StaminaNoRegen)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_FullStamina)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Throwing)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Hitting)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Death)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_PerfectGuarding)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_SuccessPerfectGuarding);

	// Data Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Stamina_Enough);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cost_Stamina_UnEnough);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Gain_Experience);

	// GameplayEffect Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GE_Player_Stats);
	
}
