// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace TwoMinGameplayTag
{
	// Input Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle);		// Toggle
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_Run);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_LockOn);

	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHold);	// Hold

	// Weapon Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Shield);
	
	// Player Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LightAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HeavyAttack_OneHand);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LockOn);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);

	// Player Event Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	
	// Player State Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_LockOn);
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Rolling);

	// Enemy Weapon Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	// Enemy Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);

	// Shard Ability Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	
	// Shard Event Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)

	// Shard State Tags
	PROJECT_2M_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Invincible);
}
